# Generated by Django 4.2.4 on 2023-08-24 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nshm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seismichazardmodel",
            name="source_logic_tree",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nshm.sourcelogictree",
            ),
        ),
        migrations.AlterField(
            model_name="sourcelogictree",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="users can search on this so please add some useful text",
            ),
        ),
    ]
