# Generated by Django 4.2.4 on 2023-08-24 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nshm", "0002_seismichazardmodel_source_logic_tree_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceLogicTreeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50)),
                ("notes", models.TextField()),
                ("inversion_toshi_id", models.CharField(max_length=50)),
                ("background_toshi_id", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SourceLogicTreeWeightedComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                (
                    "source_logic_tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nshm.sourcelogictree",
                    ),
                ),
                (
                    "source_logic_tree_component",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nshm.sourcelogictreecomponent",
                    ),
                ),
            ],
        ),
    ]
