# Generated by Django 4.2.4 on 2023-08-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nshm', '0003_sourcelogictreecomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelogictreecomponent',
            name='tectonic_region',
            field=models.CharField(choices=[('CRUSTAL', 'Crustal'), ('SUBDUCTION', 'Subduction'), ('INTERFACE', 'Interface')], default='CRUSTAL', max_length=10),
            preserve_default=False,
        ),
    ]
