# Generated by Django 4.2.4 on 2023-08-24 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nshm", "0004_sourcelogictreecomponent_tectonic_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcelogictreeweightedcomponent",
            name="source_logic_tree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slt_weighted_components",
                to="nshm.sourcelogictree",
            ),
        ),
        migrations.AlterField(
            model_name="sourcelogictreeweightedcomponent",
            name="source_logic_tree_component",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slt_weighted_components",
                to="nshm.sourcelogictreecomponent",
            ),
        ),
    ]
