# Generated by Django 4.2.4 on 2023-08-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nshm", "0006_alter_seismichazardmodel_source_logic_tree"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcelogictreecomponent",
            name="group",
            field=models.CharField(
                choices=[
                    ("Slab", "Slab"),
                    ("Hikurangi", "Hik"),
                    ("Puysegur", "Puy"),
                    ("Crustal", "Cru"),
                ],
                default="HIK",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
