# Generated by Django 4.2.4 on 2023-08-24 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nshm", "0007_sourcelogictreecomponent_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seismichazardmodel",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="seismichazardmodel",
            name="source_logic_tree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seismic_hazard_models",
                to="nshm.sourcelogictree",
            ),
        ),
        migrations.AlterField(
            model_name="sourcelogictree",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="users can search on this.. please add some useful text here",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourcelogictree",
            name="version",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="sourcelogictreecomponent",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
