# Generated by Django 4.2.4 on 2023-08-25 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nshm", "0008_alter_seismichazardmodel_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GMCM_LogicTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=30)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="seismichazardmodel",
            name="gmcm_logic_tree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seismic_hazard_models",
                to="nshm.gmcm_logictree",
            ),
        ),
    ]
