# Generated by Django 4.2.4 on 2023-08-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nshm', '0009_gmcm_logictree_seismichazardmodel_gmcm_logic_tree'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GMCM_LogicTree',
            new_name='GMCMLogicTree',
        ),
    ]
