# Generated by Django 4.2.4 on 2023-08-28 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nshm', '0011_locationlist_hazardsolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenquakeHazardTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_task_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('config_info', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('part_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_tasks', to='nshm.seismichazardmodel')),
            ],
        ),
    ]
