# Generated by Django 4.2.4 on 2023-08-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nshm', '0012_openquakehazardtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenquakeHazardTask',
        ),
    ]
