# Generated by Django 4.2.4 on 2023-09-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nshm", "0013_delete_openquakehazardtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="hazardsolution",
            name="typename",
            field=models.CharField(default="HazardSolution", max_length=50),
        ),
    ]
