# Generated by Django 4.2.4 on 2023-09-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nshm", "0014_hazardsolution_typename"),
    ]

    operations = [
        migrations.AddField(
            model_name="seismichazardmodel",
            name="typename",
            field=models.CharField(default="SeismicHazardModel", max_length=50),
        ),
    ]
