# Generated by Django 4.2.4 on 2023-09-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nshm", "0015_seismichazardmodel_typename"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seismichazardmodel",
            name="typename",
        ),
    ]
