# Generated by Django 4.2.5 on 2023-11-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nshm", "0016_remove_seismichazardmodel_typename"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SourceLogicTreeWeightedComponent",
            new_name="SourceLogicTreeBranch",
        ),
        migrations.RenameModel(
            old_name="SourceLogicTreeComponent",
            new_name="SourceLogicTreeSource",
        ),
    ]
