name: deploy-aws-lambda

on:
  push:
    branches:
      - deploy-test
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:      

jobs:
  call-test-workflow:
    uses: ./.github/workflows/dev.yml
    secrets: inherit

  call-deploy-workflow:
    needs: call-test-workflow
    uses: GNS-Science/nshm-github-actions/.github/workflows/deploy-to-aws.yml@main
    with:
      python-version: '3.10'
      smoketest-query: "query {about, current_model_version}"
    secrets: inherit
